### PR TITLE
Add additional geo functions to fullDDL

### PR DESCRIPTION
**Pull request by hhakimi53**
The changelist does not have geo functions contains() and isValid() and will be addressed in ENG-9657.

### CODE REVIEW

**Comment by BillWhite** [comment]
Looks fine to me.

**Comment by hhakimi53** [comment]
Thanks for looking at it. Currently waiting for Jenkins run to complete and will check in the changes once Jenkins is blue.

**Comment by hhakimi53** [comment]
There were two failures in pro-junit run and both of them are known TestExport issues for which fixes will be going into master soon.
TestExportLiveDDLSuite.testExportDataAfterCatalogUpdate()
TestExportRejoin.testExportAndThenRejoinClearsExportOverflow()

**Comment by hhakimi53** [comment]
Just realized the area function was not included in the fullDDL. Will push in another change for the same.

**Pull request merged**
