### PR TITLE
ENG-19689.  Fix show license in release-9.3.x.

### PR DESCRIPTION
**Pull request by rmorgenstein**
Backport show license fix.

### CODE REVIEW

**Comment by dave-voltdb** [comment]
conflicts to resolve...

**Comment by luyangco** [comment]
> conflicts to resolve...

Oh I already did that :)

**Comment by dave-voltdb** [comment]
I'm confused as to whether it's intended to merge this into 9.3.x.

**Comment by luyangco** [comment]
@rmorgenstein I close this because the fix has already went in v9.3.x.

**Pull request closed without merging**
