### PR TITLE
ENG-13242: Delete-as-you-go iterators for large temp tables

### PR DESCRIPTION
**Pull request by wolffcm**
In addition to supporting delete-as-you-go, I made some other changes:
- I removed `const` keyword from methods in `TableTuple` that actually modify the tuple storage
- I did a refactoring of TableIterator.  Mostly I removed unneeded redundant state, and reordered how member variables are initialized to be more consistent.
- Found a bug in how the "volatile" bit is set when inserting volatile NValues into a tuple.  This change is in `TableTuple::setNValue`.

### CODE REVIEW

**Comment by yzhang1991** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ee/common/tabletuple.h, line 742 at r1](https://reviewable.io:443/reviews/voltdb/voltdb/5066#-L20kzr3ZFZtIJ_Mr2_J:-L20kzr3ZFZtIJ_Mr2_K:b6rd6wd) ([raw file](https://github.com/voltdb/voltdb/blob/86c7a843e58b5547c3206b583959f723d85ad638/src/ee/common/tabletuple.h#L742)):*
> ```objc
>         // If the nvalue is not to be inlined, we will be storing a
>         // pointer in this tuple, and this pointer may be pointing to
>         // volatile storage (i.e., a large temp table block).
> ```

Or PoolBackedTupleStorage

---

*[tests/ee/storage/LargeTempTableTest.cpp, line 551 at r1](https://reviewable.io:443/reviews/voltdb/voltdb/5066#-L21L-JMNZ4k5uJ4XpBo:-L21L-JMNZ4k5uJ4XpBp:brd6xnu) ([raw file](https://github.com/voltdb/voltdb/blob/86c7a843e58b5547c3206b583959f723d85ad638/tests/ee/storage/LargeTempTableTest.cpp#L551)):*
> ```cpp
>     //
>     // Insert enough tuples for 3 blocks.
>     for (i = 0; i < 5000; ++i) {
> ```

Maybe we want to see the 1st block is release after we start to scan the 2nd block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/voltdb/voltdb/5066)*

**Comment by wolffcm** [comment]
*[src/ee/common/tabletuple.h, line 742 at r1](https://reviewable.io:443/reviews/voltdb/voltdb/5066#-L20kzr3ZFZtIJ_Mr2_J:-L22JFG_QZWndIDapqSN:bav9tgw) ([raw file](https://github.com/voltdb/voltdb/blob/86c7a843e58b5547c3206b583959f723d85ad638/src/ee/common/tabletuple.h#L742)):*
<details><summary><i>Previously, yzhang1991 (Yiqun Zhang) wrote…</i></summary><blockquote>

Or PoolBackedTupleStorage
</blockquote></details>

I'm not sure what you mean by this comment.  Can you clarify?  A pointer to a non-inlined value would not be pointing to PoolBackedTupleStorage, since PoolBackedTupleStorage is just a mechanism for managing storage for only inlined data.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/voltdb/voltdb/5066)*

**Comment by wolffcm** [comment]
*[tests/ee/storage/LargeTempTableTest.cpp, line 551 at r1](https://reviewable.io:443/reviews/voltdb/voltdb/5066#-L21L-JMNZ4k5uJ4XpBo:-L22R0M0d6VoMPYtUdlY:bategie) ([raw file](https://github.com/voltdb/voltdb/blob/86c7a843e58b5547c3206b583959f723d85ad638/tests/ee/storage/LargeTempTableTest.cpp#L551)):*
<details><summary><i>Previously, yzhang1991 (Yiqun Zhang) wrote…</i></summary><blockquote>

Maybe we want to see the 1st block is release after we start to scan the 2nd block.
</blockquote></details>

Good idea, I've added these checks to the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/voltdb/voltdb/5066)*

**Comment by wolffcm** [comment]
*[tests/ee/storage/LargeTempTableTest.cpp, line 551 at r1](https://reviewable.io:443/reviews/voltdb/voltdb/5066#-L21L-JMNZ4k5uJ4XpBo:-L22R3Ykv0upTGtAzvgK:b-896fix) ([raw file](https://github.com/voltdb/voltdb/blob/86c7a843e58b5547c3206b583959f723d85ad638/tests/ee/storage/LargeTempTableTest.cpp#L551)):*
<details><summary><i>Previously, wolffcm (Christopher M. Wolff) wrote…</i></summary><blockquote>

Good idea, I've added these checks to the test.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/voltdb/voltdb/5066)*

**Pull request merged**
