### PR TITLE
ENG-7527 enable catalog updates with export properties changes

### PR DESCRIPTION
**Pull request by vtkstef**

### CODE REVIEW

**Comment by akhanzode** [comment]
Can you add tests with LocalServer that modify this at runtime and test expected result of running export clients. Also test the cases when we will not allow changes.

**Comment by vtkstef** [comment]
Considering the scope of the change (a couple of lines in CatalogDiffEngine) do you believe that a localServer test case would take other code paths which differ from the ones already tested in TestCatalogDiffs?

**Comment by akhanzode** [comment]
Its not so much for diff path but test/code coverage so if accidental change breaks this we will catch.

**Comment by vtkstef** [comment]
It's not just the diffing. It calls compileDeployment which will create an instance of the configured and modified export connector. I don't see yet what would make a local server test compelling.

**Pull request merged**
