### PR TITLE
Fix compilation error on Mac.

### PR DESCRIPTION
**Pull request by nshi**

### CODE REVIEW

**Comment by jhugg** [comment]
Send to paul/xin?

**Comment by wolffcm** [comment]
Looks fine to me too.  Just curious, what was the compilation error?  It doesn't happen on my machine.

**Comment by nshi** [comment]
I upgraded clang on my Mac yesterday and it started failing because it thinks the pointer `this` can never be `NULL` in a proper C++ context.

**Comment by paulmartel** [comment]
WOW! So I guess this is incorrect code that only works by taking advantage of g++ implementation details:

        AbstractExpression* ae = NULL;
        if (std::string("NULL") == ae->AbstractExpression::debug()) {
            cout << "g++ rocks!";
        }

By extension, what I should really be doing to avoid undefined behavior in my robust library code is to make all of my member functions private and wrap each one in a public static member function that tests for null before calling the member function. That should cover all the undefined cases.

That's one hard-core coding standard. Do the clang tools offer a utility for generating stubs for these wrappers and rewriting callers to call them? It's probably on their roadmap.

The workaround implemented here is MOSTLY harmless -- most calls to debug will have already crashed if this is null. But I don't know if I consider this progress. In the non-virtually-called edge case above, it trades one technically undefined behavior that mostly works for another practically undefined behavior that mostly crashes.   Thanks, clang, for saving us from an undeserved success.

**Pull request merged**
