### PR TITLE
ENG-6422 make guava TypeToken compilable with Java 8

### PR DESCRIPTION
**Pull request by vtkstef**

### CODE REVIEW

**Comment by vtkstef** [comment]
R.by: @akhanzode

**Comment by akhanzode** [comment]
Can you also run this branch through java8 and test jdbcloader which is only user of type token. There is a unit test for it but that runs under 1.7 or 1.8 not 1.6

**Comment by vtkstef** [comment]
yes TestJDBCLoader works on java8

**Comment by vtkstef** [comment]
passes jenkins running on java8 machines

**Pull request merged**
