### PR TITLE
Remove unnecessary regex during bulkloading

### PR DESCRIPTION
**Pull request by rkennedy-mode**
During bulk loading, VoltDB translates any string values provided to the types of the underlying columns. This coercion sometimes utilizes regular expressions, which can be more costly than necessary.

These changes avoid regular expressions in those situations to make the bulk loading more efficient. When importing 28M row, 38 column, 5GB CSV file this overhead is quite noticeable for our application and these changes make a material difference.

I've built and packaged VoltDB and run TestParameterConverter and TestSQLParser locally to look for any breakages and don't see anything.

We'd appreciate if this can be backported to 8.x.

### CODE REVIEW

**Comment by luyangco** [comment]
It looks good to me, has anyone taken care of it? If not, I'm happy to do the test and merge the code.
@benjaminballard, does he need to sign up NDA to get the patch merged?

**Comment by benjaminballard** [comment]
> It looks good to me, has anyone taken care of it? If not, I'm happy to do the test and merge the code.
> @benjaminballard, does he need to sign up NDA to get the patch merged?

You can merge it. We have an NDA on file for Ryan Kennedy at Mode.

**Comment by luyangco** [comment]
@rkennedy-mode Merged into master externally, you can close this. We gonna back port it soon.

**Comment by rkennedy-mode** [comment]
Closing, finally. 😂

**Pull request closed without merging**
