### PR TITLE
ENG-8437:

### PR DESCRIPTION
**Pull request by manjujames**
Fixes to classes included in client side 1.6 build so that they will compile correctly.
Now compile with -source 1.6 with the required -bootclasspath option as well.

### CODE REVIEW

**Comment by BillWhite** [comment]
Will these changes require Eclipse changes as well?

**Comment by manjujames** [comment]
No, this won't require Eclipse changes.

**Comment by akhanzode** [comment]
This looks ok to me. If @paulmartel is ok with lexer changes and jenkins is happy.

**Comment by paulmartel** [comment]
Looks good to me. I am a little shocked -- do we really only use this feature (client side) for this one rather uninteresting case?

**Comment by manjujames** [comment]
That's right. We also use capture labels in HSQLLexer, but that is server side only.

**Pull request merged**
