### PR TITLE
Merge recent commits from master into geospatial topic branch

### PR DESCRIPTION
**Pull request by wolffcm**
Conflicts:
-        build.py
-        buildtools.py
-        src/ee/expressions/functionexpression.h
-        src/hsqldb19b3/org/hsqldb_voltpatches/FunctionForVoltDB.java
-        src/hsqldb19b3/org/hsqldb_voltpatches/FunctionSQL.java
-        third_party/cpp/.gitignore

### CODE REVIEW

**Comment by BillWhite** [comment]
I looked at build.py and buildtools.py.  They look perfect to me.

Was it easier to merge this time?  I made some changes to the master version when we were working on the regexp functions which I hoped would make the merge more straightforward.

**Comment by wolffcm** [comment]
Yes, much easier.  I didn't need to edit much by hand at all.

**Comment by wolffcm** [comment]
@BillWhite, @hhakimi53:

It turns out I forgot to push the recent master commits that Huzefa merged from the release-5.8.x branch.  So I guess that's why changes to build*.py looked perfect... they were totally unchanged.

I added a few more commits to fix a pro snapshot test that was failing (it looks like new code in the community repro, but I moved the code from the pro repo).  The pro pull request is here:

https://github.com/VoltDB/pro/pull/1128

I also renumbered the geo functions starting 21000 at Huzefa's suggestion.

Bill, Huzefa, could you guys check my work to make sure I didn't mess anything up?  Especially changes to the build scripts should be more interesting now.

**Comment by hhakimi53** [comment]
Merge changes from master involving new SQL functions (I have not looked at buildtools.py in details) for Huawei, are complete and everything looks good, nothing messed up :-). 
Thanks Chris for resolving those merge conflicts and renumbering the geo functions to start from 21000.

**Comment by BillWhite** [comment]
This looks good.  The python build scripts need some work, but it is not really crucial.  I'll do it in another round of changes.  The only problem is that the resulting makefile is slightly out of order, and there is a target which is logically missing, though we don't use it.

**Comment by wolffcm** [comment]
Thanks guys.  Jenkins is about to shut down it looks like, I'll wait until I see a clean build/test cycle, but I'll merge this shortly afterwards.

**Comment by wolffcm** [comment]
It looks like the pro test that I thought I fixed is not passing in Jenkins.  I'll need to look at it again later today.

**Pull request merged**
